CREATE TABLE `category`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `pid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '0' COMMENT '父分类ID',
  `category_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '分类名称',
  `category_full_name` varchar(255) NULL COMMENT '分类全名',
  `category_code` varchar(255) NULL COMMENT '分类编码',
  `category_icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '分类图标',
  `category_picture` json NULL COMMENT '分类图片',
  `category_level` tinyint UNSIGNED NULL COMMENT '层级：1一级 2二级',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `c_status` varchar(1) NULL DEFAULT '1' COMMENT '状态',
  `is_show` varchar(1) NULL DEFAULT '1' COMMENT '是否展示',
  `is_index` varchar(1) NULL COMMENT '首页推荐',
  `remark` varchar(255) NULL COMMENT '描述',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品分类表' ROW_FORMAT = Dynamic;

CREATE TABLE `cms_banner`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '标题',
  `distribution_site` tinyint NOT NULL COMMENT '投放位置：1首页 2分类页',
  `img_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '图片地址',
  `href_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '跳转地址',
  `c_type` tinyint NULL DEFAULT NULL COMMENT '跳转类型',
  `product_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '关联商品ID',
  `category_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '关联分类ID',
  `is_show` tinyint NOT NULL COMMENT '是否展示',
  `f_sort_code` bigint NULL DEFAULT NULL COMMENT '排序码',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '轮播配置表' ROW_FORMAT = Dynamic;

CREATE TABLE `company_manage`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `c_status` varchar(10) NOT NULL COMMENT '状态(1启用 0停用)',
  `company_name` varchar(200) NULL COMMENT '公司名称',
  `company_short_name` varchar(100) NULL COMMENT '公司简称',
  `credit_code` varchar(255) NULL COMMENT '统一社会信用代码',
  `legal_person` varchar(255) NULL COMMENT '法人代表',
  `registered_capital` decimal(18, 2) NULL COMMENT '注册资本',
  `establish_date` date NULL COMMENT '成立日期',
  `appendix` json NULL COMMENT '相关附件',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id` DESC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '公司主体信息表' ROW_FORMAT = Dynamic STATS_PERSISTENT = 0;

CREATE TABLE `enterprise_standard`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `enterprise_name` varchar(255) NULL COMMENT '标准名称',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id` DESC) USING BTREE,
  UNIQUE INDEX `uk_enterprise_name`(`enterprise_name`) USING BTREE COMMENT '标准名称唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '执行标准管理表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_brand`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `brand_name` varchar(255) NOT NULL COMMENT '品牌名称',
  `is_show` varchar(255) NULL COMMENT '显示状态(0:隐藏,1:显示)',
  `brand_pic` json NULL COMMENT '品牌图片',
  `brand_en_code` varchar(255) NULL COMMENT '英文名称',
  `sort_order` tinyint NULL COMMENT '排序',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_brand_name`(`brand_name`) USING BTREE COMMENT '品牌名称唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品品牌表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_category_relation`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `category_id` varchar(255) NULL COMMENT '商品分类id',
  `spu_id` varchar(255) NULL COMMENT '商品id',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品分类关联表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_details`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `spu_id` varchar(255) NULL COMMENT 'spu_id',
  `spu_code` varchar(255) NULL COMMENT 'spu编码',
  `national_standard` varchar(255) NULL COMMENT '国家标准',
  `enterprise_standard` varchar(255) NULL COMMENT '企业标准',
  `test_report_files` varchar(255) NULL COMMENT '检测报告',
  `detail_pic` json NULL COMMENT '详情图片',
  `certification_mark` varchar(255) NULL COMMENT '认证标志',
  `warranty_period` int NULL COMMENT '保质期',
  `spu_element` varchar(255) NULL COMMENT '成分',
  `use_scope` varchar(255) NULL COMMENT '适用范围',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品详情表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_package`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `package_name` varchar(255) NULL COMMENT '包装名称',
  `number_pieces` int NULL DEFAULT 1 COMMENT '每件数量',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_package_name`(`package_name`) USING BTREE COMMENT '包装名称唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品包装表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_sku`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `spu_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品SPUID',
  `spu_code` varchar(255) NULL COMMENT 'SPU编码',
  `sku_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'SKU编码',
  `goods_spec_id` varchar(255) NOT NULL COMMENT '规格详情ID',
  `sku_spec` varchar(255) NULL COMMENT 'sku规格',
  `sku_spec_name` varchar(255) NULL COMMENT '规格型号',
  `sku_pic` json NULL COMMENT 'SKU图片',
  `sku_status` varchar(255) NULL COMMENT '状态：0下架 1外部上架 2内部上架',
  `not_show_types` varchar(255) NULL COMMENT '不可见客户类型',
  `attrs_text` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '规格文案快照',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品SKU表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_sku_attr`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `goods_sku_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SKU ID',
  `attr_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '属性名',
  `attr_value` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '属性值',
  `sort_order` int NULL COMMENT '排序',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'SKU属性值表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_spec_relation`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `spu_id` varchar(255) NULL COMMENT '商品SPUID',
  `spec_name` varchar(255) NULL COMMENT '规格名称',
  `spec_unit` varchar(255) NULL COMMENT '单位',
  `net_weight` decimal(10, 2) NULL COMMENT '净重',
  `original_price` decimal(10, 2) NULL COMMENT '原价',
  `goods_package` varchar(255) NULL COMMENT '包装',
  `not_show_types` varchar(255) NULL COMMENT '不可见客户类型',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品规格详情关联表' ROW_FORMAT = Dynamic;

CREATE TABLE `goods_spu`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `spu_code` varchar(255) NULL COMMENT '商品编码',
  `spu_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品名称',
  `en_name` varchar(255) NULL COMMENT '英文名称',
  `spu_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '商品描述',
  `spu_pics` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '商品图片',
  `spu_status` varchar(20) NULL COMMENT '状态：0下架 1外部上架 2内部上架',
  `brand_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '品牌名称',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品SPU表' ROW_FORMAT = Dynamic;

CREATE TABLE `market_entity_info`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `c_status` varchar(10) NULL COMMENT '状态(1启用，0停用)',
  `mark_code` varchar(255) NULL COMMENT '唛头',
  `mark_name` varchar(255) NULL COMMENT '唛头名称',
  `mark_type` varchar(255) NULL COMMENT '类型(1城市代理商，2城市服务商，3授权经销商，4区域独家经销商，5大区)',
  `mark_level` int NULL COMMENT '等级',
  `qywx_dpt_id` int NOT NULL COMMENT '企业微信部门ID',
  `qywx_dpt_name` varchar(255) NULL COMMENT '企业微信部门名称',
  `sales_company_id` varchar(255) NULL COMMENT '销售公司主体',
  `sales_area` json NULL COMMENT '可销售区域',
  `regional_manager_id` varchar(255) NULL COMMENT '区域经理ID',
  `service_manager` varchar(255) NULL COMMENT '客服经理ID',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT 0 COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int ZEROFILL NULL DEFAULT 0 COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_mark_code`(`mark_code`) USING BTREE COMMENT '唛头唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '经营实体信息表' ROW_FORMAT = Dynamic;

CREATE TABLE `market_types`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `market_type_name` varchar(255) NULL COMMENT '类型名称',
  `en_code` varchar(255) NULL COMMENT '类型编码',
  `type_dec` text NULL COMMENT '描述',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT 0 COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT 0 COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '经营主体类型表' ROW_FORMAT = Dynamic;

CREATE TABLE `member_address`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `member_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID',
  `receiver` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '收货人',
  `contact` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系方式',
  `province_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '省编码',
  `city_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '市编码',
  `county_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '区县编码',
  `full_location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '省市区文案',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '详细地址',
  `is_default` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否默认地址',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  INDEX `idx_member_address_member_id`(`member_id` ASC) USING BTREE,
  INDEX `idx_member_address_member_default`(`member_id` ASC, `is_default` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '会员地址表' ROW_FORMAT = Dynamic;

CREATE TABLE `member_relation`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `member_fid` varchar(255) NULL COMMENT '人员主键',
  `market_fid` varchar(255) NULL COMMENT '唛头主键',
  `member_identity` varchar(50) NULL COMMENT '人员身份',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT 0 COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT 0 COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_member_market`(`member_fid`, `market_fid`) USING BTREE COMMENT '人员与mark唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '人员关联唛头表' ROW_FORMAT = Dynamic;

CREATE TABLE `member_user`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `c_status` varchar(10) NOT NULL DEFAULT '1' COMMENT '状态',
  `user_id` varchar(255) NULL COMMENT '企微帐号',
  `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '手机号',
  `nickname` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '昵称',
  `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '头像',
  `gender` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '未知' COMMENT '性别(1男，2女，3保密)',
  `openid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '微信OpenID',
  `union_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '微信UnionID',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT 0 COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT 0 COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_member_user_id`(`user_id`) USING BTREE COMMENT '企微id唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '客户人员信息表' ROW_FORMAT = Dynamic;

CREATE TABLE `national_standard`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `national_name` varchar(255) NULL COMMENT '标准名称',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_national_name`(`national_name`) COMMENT '标准名称唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '国标管理表' ROW_FORMAT = Dynamic;

CREATE TABLE `spec_info`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `spec_name` varchar(255) NULL COMMENT '规格名称',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_spec_name`(`spec_name`) USING BTREE COMMENT '规格名称唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品规格表' ROW_FORMAT = Dynamic;

CREATE TABLE `unit_info`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `unit_name` varchar(255) NULL COMMENT '单位名称',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_unit`(`unit_name`) USING BTREE COMMENT '单位名唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '商品单位表' ROW_FORMAT = Dynamic;

CREATE TABLE `wework_dpt`  (
  `dpt_id` int NOT NULL COMMENT '主键',
  `dpt_name` varchar(255) NULL COMMENT '部门名称',
  `parent_id` int NULL COMMENT '父部门id',
  `dpt_order` int NULL COMMENT '部门排序',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`dpt_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '企微部门列表' ROW_FORMAT = Dynamic;

