CREATE TABLE `market_entity_info`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `c_status` varchar(10) NULL COMMENT '状态(1启用，0停用)',
  `mark_code` varchar(255) NULL COMMENT '唛头',
  `mark_name` varchar(255) NULL COMMENT '唛头名称',
  `mark_type` varchar(255) NULL COMMENT '类型(1城市代理商，2城市服务商，3授权经销商，4区域独家经销商，5大区)',
  `mark_level` int NULL COMMENT '等级',
  `qywx_dpt_id` int NOT NULL COMMENT '企业微信部门ID',
  `qywx_dpt_name` varchar(255) NULL COMMENT '企业微信部门名称',
  `sales_company_id` varchar(255) NULL COMMENT '销售公司主体',
  `sales_area` json NULL COMMENT '可销售区域',
  `regional_manager_id` varchar(255) NULL COMMENT '区域经理ID',
  `service_manager` varchar(255) NULL COMMENT '客服经理ID',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_mark_code`(`mark_code`) USING BTREE COMMENT '唛头唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '经营实体信息表' ROW_FORMAT = Dynamic;

CREATE TABLE `market_types`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `market_type_name` varchar(255) NULL COMMENT '类型名称',
  `en_code` varchar(255) NULL COMMENT '类型编码',
  `type_dec` text NULL COMMENT '描述',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '经营主体类型表' ROW_FORMAT = Dynamic;

CREATE TABLE `member_relation`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `member_fid` varchar(255) NULL COMMENT '人员主键',
  `market_fid` varchar(255) NULL COMMENT '唛头主键',
  `member_identity` varchar(50) NULL COMMENT '人员身份',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_member_market`(`member_fid`, `market_fid`) USING BTREE COMMENT '人员与mark唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '人员关联唛头表' ROW_FORMAT = Dynamic;

CREATE TABLE `member_user`  (
  `f_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键',
  `c_status` varchar(10) NOT NULL DEFAULT '1' COMMENT '状态',
  `user_id` varchar(255) NULL COMMENT '企微帐号',
  `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '手机号',
  `nickname` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '昵称',
  `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '头像',
  `gender` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '未知' COMMENT '性别(1男，2女，3保密)',
  `openid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '微信OpenID',
  `union_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '微信UnionID',
  `f_tenant_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '租户id',
  `f_delete_mark` int NULL DEFAULT NULL COMMENT '删除标志',
  `f_delete_time` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `f_delete_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '删除用户',
  `f_version` int NULL DEFAULT NULL COMMENT '乐观锁',
  `f_flow_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程id',
  `f_flow_task_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '流程任务主键',
  `f_flow_state` int NULL DEFAULT NULL COMMENT '流程任务状态',
  `f_creator_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '创建用户',
  `f_last_modify_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '修改用户',
  `f_creator_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `f_last_modify_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`f_id`) USING BTREE,
  UNIQUE INDEX `uk_member_user_id`(`user_id`) USING BTREE COMMENT '企微id唯一'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '客户人员信息表' ROW_FORMAT = Dynamic;

