spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.60.85:3306/city_mall_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: city_mall_db
    password: D3ySCbr8MsiJ74tP

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 5s
      password: 123456

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-migration-naming: true